name: Update File and Push

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update file content
      run: |
        echo "New content" > test.txt

    - name: Commit changes
      run: |
        git config --global user.name 'Saurabh Talele'
        git config --global user.email 'Saurabh.Talele@bentley.com'
        git add .
        git commit -m "Update file content"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
